### ISSUE TITLE
Canary workflow for commiting new services

### ISSUE THREAD

**Issue by BagheriReza** [scp756-221/term-project-cloudriven#14]
The workflow of deploying the new version:
Develop and prepare the deployment YAML file for the new version (update)
Using istio VirtualService‘s DestinationRule feature to split the traffic between the old version and a new version
1. Deploying the new update
2. If there is no bug move to Step 8
3. Reroute the traffic to the old version
4. Fix the bug and redeploy a new version
5. Router part of traffic to new service
6. If there is a bug move to Step 4
7. Delete old version
8. The process of deploying a new version is finished.
@bingsoorim @beinfluential88 @rezvanm @BagheriReza

**Comment by bingsoorim** [comment]
Closing this issue.
